src = ["channels-stubs", "tests"]
target-version = "py311"

[lint]
ignore = ["E501", "N802", "N818"]
select = ["B", "C90", "E", "F", "I", "N", "N", "PL", "Q", "W"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]  # noqa
