from asgiref.testing import ApplicationCommunicator as BaseApplicationCommunicator
from asgiref.typing import ASGIReceiveEvent, ASGISendEvent

def no_op() -> None: ...

class ApplicationCommunicator(BaseApplicationCommunicator):
    async def send_input(self, message: ASGIReceiveEvent) -> None: ...
    async def receive_output(self, timeout: float = ...) -> ASGISendEvent: ...
