from typing import Any

from channels.consumer import AsyncConsumer

class AsyncHttpConsumer(AsyncConsumer):
    body: list[bytes]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def send_headers(
        self,
        *,
        status: int = 200,
        headers: dict[str, str] | list[tuple[str, str]] | None = None,
    ) -> None: ...
    async def send_body(self, body: bytes, *, more_body: bool = False) -> None: ...
    async def send_response(self, status: int, body: bytes, **kwargs: Any) -> None: ...
    async def handle(self, body: bytes) -> None: ...
    async def disconnect(self) -> None: ...
    async def http_request(self, message: dict[str, Any]) -> None: ...
    async def http_disconnect(self, message: dict[str, Any]) -> None: ...
