name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uvt
        uses: astral-sh/setup-uv@v5
        with:
            enable-cache: true
            python-version: 3.11
      - name: Install tox
        run: uv tool install tox --with tox-uv --with tox-gh
      - name: Run lint
        run: tox -e lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
      fail-fast: false
    env:
      TOX_GH_MAJOR_MINOR: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: uv tool install tox --with tox-uv --with tox-gh
      - name: Run tests
        run: tox
